### ISSUE TITLE
link error AWS with SSL on debian 9 64 bit

### ISSUE THREAD

**Issue by b201b201** [AdaCore/aws#10] opened 2017-08-28 21:05 UTC
Hi!
The following problem was posted on AWS-mailing list 2017-08-20 and
did not receive any reply.

Having a production machine on 64 bit debian 8 I got

bnl@prod:~$ apt-cache pkgnames | grep -i libssl | sort
libssl1.0.0
libssl1.0.0-dbg
libssl-dev
libssl-doc
libssl-ocaml
libssl-ocaml-dev

and a dev machine on 64 bit debian 9 with

bnl@tp:~/svn/bnlbot/botstart/bot-1-0/source/ada$ apt-cache pkgnames |
grep libssl | sort
libssl1.0.0
libssl1.0.2
libssl1.0-dev
libssl1.1
libssl-dev
libssl-doc
libssl-ocaml
libssl-ocaml-dev
bnl@tp:~/svn/bnlbot/botstart/bot-1-0/source/ada$

To build AWS with ssl support I set

SOCKET    = openssl

in makefile.conf

Building AWS itself works on both debians but using it does not work on
debian 9

   [link]         poll.adb
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__locking__initializeXnn':
aws-net-ssl__openssl.adb:(.text+0x6b0a): undefined reference to
`CRYPTO_set_id_callback'
aws-net-ssl__openssl.adb:(.text+0x6b14): undefined reference to
`CRYPTO_set_locking_callback'
aws-net-ssl__openssl.adb:(.text+0x6b1e): undefined reference to
`CRYPTO_set_dynlock_create_callback'
aws-net-ssl__openssl.adb:(.text+0x6b28): undefined reference to
`CRYPTO_set_dynlock_lock_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__ciphers':
aws-net-ssl__openssl.adb:(.text+0x7e76): undefined reference to
`SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__signature__3':
aws-net-ssl__openssl.adb:(.text+0x9248): undefined reference to
`EVP_MD_CTX_create'
aws-net-ssl__openssl.adb:(.text+0x931e): undefined reference to
`EVP_MD_CTX_destroy'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__set_accept_state':
aws-net-ssl__openssl.adb:(.text+0xb1aa): undefined reference to
`SSL_set_tmp_rsa_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__version':
aws-net-ssl__openssl.adb:(.text+0xd9e9): undefined reference to
`SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xda86): undefined reference to
`SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdaa0): undefined reference to
`SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdaba): undefined reference to
`SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdad4): undefined reference to
`SSLeay_version'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl___elabb':
aws-net-ssl__openssl.adb:(.text+0xe177): undefined reference to
`CRYPTO_num_locks'
aws-net-ssl__openssl.adb:(.text+0xe2ff): undefined reference to
`SSL_load_error_strings'
aws-net-ssl__openssl.adb:(.text+0xe304): undefined reference to
`SSL_library_init'
aws-net-ssl__openssl.adb:(.text+0xe31e): undefined reference to
`SSL_CTX_get_ex_new_index'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl___elabs':
aws-net-ssl__openssl.adb:(.text+0xe492): undefined reference to `SSLeay'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):
In function `aws__net__ssl__locking__initializeXnn':
aws-net-ssl__openssl.adb:(.text+0x6b36): undefined reference to
`CRYPTO_set_dynlock_destroy_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16c0):
undefined reference to `SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16c8):
undefined reference to `SSLv23_server_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16d0):
undefined reference to `SSLv23_client_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1720):
undefined reference to `SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1728):
undefined reference to `SSLv23_server_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1730):
undefined reference to `SSLv23_client_method'
collect2: error: ld returned 1 exit status
gprbuild: link of poll.adb failed
makefile:67: receptet för målet ”adabot” misslyckades
make[1]: *** [adabot] Fel 4
make[1]: Lämnar katalogen
”/home/bnl/svn/bnlbot/botstart/bot-1-0/source/ada”

bnl@tp:~/svn/bnlbot/botstart/bot-1-0/source/ada$ uname -a
Linux tp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64
GNU/Linux
bnl@tp:~/svn/bnlbot/botstart/bot-1-0/source/ada$

bnl@tp:~/svn/bnlbot/botstart/bot-1-0/source/ada$ gnatls -v

GNATLS GPL 2017 (20170515-63)
Copyright (C) 1997-2017, Free Software Foundation, Inc.

Source Search Path:
   <Current_Directory>

/usr/local/ada/gpl2017/gnatx64/lib/gcc/x86_64-pc-linux-gnu/6.3.1/rts-native/adainclude

Object Search Path:
   <Current_Directory>

/usr/local/ada/gpl2017/gnatx64/lib/gcc/x86_64-pc-linux-gnu/6.3.1/rts-native/adalib

Project Search Path:
   <Current_Directory>
   /usr/local/ada/aws/gpl2017_ssl/share/gpr
   /usr/local/ada/gpl2017/gnatx64/lib/gnat
   /usr/local/ada/gpl2017/share/gpr
   /usr/local/ada/gpl2017/lib/gnat
   /usr/local/ada/gpl2017/gnatx64/x86_64-pc-linux-gnu/lib/gnat
   /usr/local/ada/gpl2017/gnatx64/x86_64-pc-linux-gnu/share/gpr
   /usr/local/ada/gpl2017/gnatx64/share/gpr
   /usr/local/ada/gpl2017/gnatx64/lib/gnat

Looking around internet it seems like openssl changed a bit between 1.0
and 1.1

How is this best handled ?

-- 
--
Björn

**Comment by TurboGit** [comment] 2017-09-03 20:08
But when you build AWS on Debian 9 you have no issue building the AWS tools, right?

Can you put here the content of the generated aws.gpr project file? It is in <prefix>/share/prefix.

Thansk.

**Comment by b201b201** [comment] 2017-09-04 06:03
On 2017-09-03 22:08, Pascal Obry wrote:
>
> But when you build AWS on Debian 9 you have no issue building the AWS 
> tools, right?
>

Yes - correct. AWS itself build fine

> Can you put here the content of the generated aws.gpr project file? It 
> is in /share/prefix.
>
I think you mean prefix/share.

--  This project has been generated by GPRINSTALL GPL 2017 (20170515) 
(x86_64-pc-linux-gnu)

library project AWS is
    type BUILD_KIND is ("default", "relocatable");
    BUILD : BUILD_KIND := external("AWS_BUILD", "default");

    for Languages use ("Ada", "C");

    case BUILD is
       when "relocatable" =>
          for Source_Dirs use ("../../include/aws.relocatable");
          for Library_Dir use "../../lib/aws.relocatable";
          for Library_Kind use "relocatable";
       when "default" =>
          for Source_Dirs use ("../../include/aws");
          for Library_Dir use "../../lib/aws";
          for Library_Kind use "static";
    end case;

    for Library_Name use "aws";

    package Naming is
       for dot_replacement use "-";
       for casing use "lowercase";

       case BUILD is
          when "relocatable" =>
             for body_suffix ("c") use ".c";
             for body_suffix ("ada") use ".adb";
             for spec_suffix ("c") use ".h";
             for spec_suffix ("ada") use ".ads";
             for spec ("ssl.thin") use "ssl-thin__openssl.ads";
             for body ("aws.net.ssl.certificate.impl") use 
"aws-net-ssl-certificate-impl__openssl.adb";
             for body ("aws.net.ssl") use "aws-net-ssl__openssl.adb";
             for body ("aws.net.poll_events.wait") use 
"aws-net-poll_events-wait__native.adb";
             for body ("aws.net.std") use "aws-net-std__gnat.adb";
             for body ("templates_parser_tasking") use 
"templates_parser_tasking__standard_tasking.adb";
             for body ("templates_parser.input") use 
"templates_parser-input__aws.adb";
             for spec ("aws.net.ssl.certificate.impl") use 
"aws-net-ssl-certificate-impl__openssl.ads";
             for spec ("templates_parser.configuration") use 
"templates_parser-configuration__aws.ads";
             for implementation_exceptions ("makefile") use ("Makefile");
          when "default" =>
             for body_suffix ("c") use ".c";
             for body_suffix ("ada") use ".adb";
             for spec_suffix ("c") use ".h";
             for spec_suffix ("ada") use ".ads";
             for spec ("ssl.thin") use "ssl-thin__openssl.ads";
             for body ("aws.net.ssl.certificate.impl") use 
"aws-net-ssl-certificate-impl__openssl.adb";
             for body ("aws.net.ssl") use "aws-net-ssl__openssl.adb";
             for body ("aws.net.poll_events.wait") use 
"aws-net-poll_events-wait__native.adb";
             for body ("aws.net.std") use "aws-net-std__gnat.adb";
             for body ("templates_parser_tasking") use 
"templates_parser_tasking__standard_tasking.adb";
             for body ("templates_parser.input") use 
"templates_parser-input__aws.adb";
             for spec ("aws.net.ssl.certificate.impl") use 
"aws-net-ssl-certificate-impl__openssl.ads";
             for spec ("templates_parser.configuration") use 
"templates_parser-configuration__aws.ads";
             for implementation_exceptions ("makefile") use ("Makefile");
       end case;
    end Naming;

    package Linker is
       case BUILD is
          when "relocatable" =>
             for Linker_Options use ("-lssl", "-ldl", "-lcrypto", "-lz");
          when "default" =>
             for Linker_Options use ("-lssl", "-ldl", "-lcrypto");
       end case;
    end Linker;

    package Install is
       for Active use "False";
    end Install;

    for Externally_Built use "True";

end AWS;

**Comment by TurboGit** [comment] 2017-09-04 15:22
Yes, I meant <prefix>/share/gpr. Thanks the project looks correct.

It looks like a wrong version of OpenSSL installed then, what is the output for:

`$ apt-cache policy libssl-dev  libssl1.0-dev
`

Also after build and installing AWS, can you try building runme demo:

`
$ cd demos/runme
$ make
`

Is this ok?

**Comment by b201b201** [comment] 2017-09-04 17:58
Thanks for looking into it.


bnl@tp:~$ apt-cache policy libssl-dev libssl1.0-dev
libssl-dev:
  Installerad: 1.1.0f-3
  Kandidat:    1.1.0f-3
  Versionstabell:
 *** 1.1.0f-3 500
        500 http://ftp.se.debian.org/debian stable/main amd64 Packages
        100 /var/lib/dpkg/status
libssl1.0-dev:
  Installerad: (ingen)
  Kandidat:    1.0.2l-2
  Versionstabell:
     1.0.2l-2 500
        500 http://ftp.se.debian.org/debian stable/main amd64 Packages
bnl@tp:~$
I'm not sure what that means...


The building of runme fails like this:
bnl@tp:~/Hämtningar/aws-gpl-2017-src/demos/runme$ make
gprbuild runme.gpr
Compile
   [Ada]          runme.adb
   [Ada]          runme_cb.adb
Bind
   [gprbind]      runme.bexch
   [Ada]          runme.ali
Link
   [link]         runme.adb
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__locking__initializeXnn':
aws-net-ssl__openssl.adb:(.text+0x6b0a): undefined reference to `CRYPTO_set_id_callback'
aws-net-ssl__openssl.adb:(.text+0x6b14): undefined reference to `CRYPTO_set_locking_callback'
aws-net-ssl__openssl.adb:(.text+0x6b1e): undefined reference to `CRYPTO_set_dynlock_create_callback'
aws-net-ssl__openssl.adb:(.text+0x6b28): undefined reference to `CRYPTO_set_dynlock_lock_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__ciphers':
aws-net-ssl__openssl.adb:(.text+0x7e76): undefined reference to `SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__signature__3':
aws-net-ssl__openssl.adb:(.text+0x9248): undefined reference to `EVP_MD_CTX_create'
aws-net-ssl__openssl.adb:(.text+0x931e): undefined reference to `EVP_MD_CTX_destroy'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__set_accept_state':
aws-net-ssl__openssl.adb:(.text+0xb1aa): undefined reference to `SSL_set_tmp_rsa_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__version':
aws-net-ssl__openssl.adb:(.text+0xd9e9): undefined reference to `SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xda86): undefined reference to `SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdaa0): undefined reference to `SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdaba): undefined reference to `SSLeay_version'
aws-net-ssl__openssl.adb:(.text+0xdad4): undefined reference to `SSLeay_version'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl___elabb':
aws-net-ssl__openssl.adb:(.text+0xe177): undefined reference to `CRYPTO_num_locks'
aws-net-ssl__openssl.adb:(.text+0xe2ff): undefined reference to `SSL_load_error_strings'
aws-net-ssl__openssl.adb:(.text+0xe304): undefined reference to `SSL_library_init'
aws-net-ssl__openssl.adb:(.text+0xe31e): undefined reference to `SSL_CTX_get_ex_new_index'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl___elabs':
aws-net-ssl__openssl.adb:(.text+0xe492): undefined reference to `SSLeay'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o): In function `aws__net__ssl__locking__initializeXnn':
aws-net-ssl__openssl.adb:(.text+0x6b36): undefined reference to `CRYPTO_set_dynlock_destroy_callback'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16c0): undefined reference to `SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16c8): undefined reference to `SSLv23_server_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x16d0): undefined reference to `SSLv23_client_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1720): undefined reference to `SSLv23_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1728): undefined reference to `SSLv23_server_method'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(aws-net-ssl__openssl.o):(.rodata+0x1730): undefined reference to `SSLv23_client_method'
collect2: error: ld returned 1 exit status
gprbuild: link of runme.adb failed
Makefile:23: receptet för målet ”all” misslyckades
make: *** [all] Fel 4
bnl@tp:~/Hämtningar/aws-gpl-2017-src/demos/runme$

**Comment by b201b201** [comment] 2017-09-04 18:01
Hmm, I wish the output from the commands were NOT interpreted as markdown commands...

**Comment by TurboGit** [comment] 2017-09-04 20:13
Ok, so runme does not compile either.

It seems that you have installed libssl-dev, but at the moment you need the older version libssl1.0-dev.

Can you install this version:

`$ sudo apt install libssl1.0-dev`

**Comment by b201b201** [comment] 2017-09-05 06:15
Ok it gets better I think.t 
I installed libssl1.0-dev. But apt then said I have 479 mb of auto-installed libs/program that can be removed. It also said libssl will be removed.
I did apt autoremove to. 

then I did make in runme
bnl@tp:~/Hämtningar/aws-gpl-2017-src/demos/runme$ make
gprbuild runme.gpr
Link
   [link]         runme.adb
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(wrappers.o): In function `__aws_X509_get_notBefore':
wrappers.c:(.text+0x1): undefined reference to `X509_getm_notBefore'
/usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(wrappers.o): In function `__aws_X509_get_notAfter':
wrappers.c:(.text+0x11): undefined reference to `X509_getm_notAfter'
collect2: error: ld returned 1 exit status
gprbuild: link of runme.adb failed
Makefile:23: receptet för målet ”all” misslyckades
make: *** [all] Fel 4

looks better - but not quite there.
Trying to build my programs I get

   [link]         test_ssl.adb
/usr/local/ada/gpl2017/gnatx64/bin/../libexec/gcc/x86_64-pc-linux-gnu/6.3.1/ld: warning: libssl.so.1.1, needed by /usr/lib/x86_64-linux-gnu/libpq.so, may conflict with libssl.so.1.0.2
/usr/local/ada/gpl2017/gnatx64/bin/../libexec/gcc/x86_64-pc-linux-gnu/6.3.1/ld: warning: libcrypto.so.1.1, needed by /usr/lib/x86_64-linux-gnu/libpq.so, may conflict with libcrypto.so.1.0.2
/usr/local/ada/gpl2017/gnatx64/bin/../libexec/gcc/x86_64-pc-linux-gnu/6.3.1/ld: /usr/local/ada/aws/gpl2017_ssl/lib/aws/libaws.a(wrappers.o): undefined reference to symbol 'X509_getm_notAfter@@OPENSSL_1_1_0'
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gprbuild: link of test_ssl.adb failed
makefile:67: receptet för målet ”adabot” misslyckades
make[1]: *** [adabot] Fel 4

which is somewhat worse since it warns about clashing libs. 
Since it do nor link yet, I did not test it to see if it works anyway.

**Comment by TurboGit** [comment] 2017-09-05 06:45
I suppose you want to clean AWS tree, and redo the setup and build as the SSL headers have been changed.

$ make clean
$ make setup
$ make
$ make install

**Comment by TurboGit** [comment] 2017-09-05 06:47
Just a note that I'm on GNU Debian/unstable (so Debian 9 + some updates) and I have no problem on my side. So I suppose that the issue is due to the environment.

**Comment by b201b201** [comment] 2017-09-05 17:16
Ok, rebuilding got it to work. I'm using libpq too, and it still complains, but the https program works. I think I'll reinstall this machine from scratch later on, but it works good enough for development as is.
Thanks for the help

**Comment by TurboGit** [comment] 2017-09-05 17:21
Good to hear this is working on your side now. Closing.

**Closed by TurboGit** 2017-09-05 17:21 UTC
